name: Build
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.3
        with:
          toolchain: stable
      - name: run vcpkg
        uses: lukka/run-vcpkg@v0
        with:
          vcpkgArguments: "gtk:x64-windows"
          vcpkgTriplet: "x64-windows"
      - name: mklink
        run:
          New-Item -ItemType SymbolicLink -Path "${{ github.workspace }}/vcpkg/installed/x64-windows/lib/gtk-3.lib" -Target "${{ github.workspace }}/vcpkg/installed/x64-windows/lib/gtk-3.0.lib"
          New-Item -ItemType SymbolicLink -Path "${{ github.workspace }}/vcpkg/installed/x64-windows/lib/gdk-3.lib" -Target "${{ github.workspace }}/vcpkg/installed/x64-windows/lib/gdk-3.0.lib"
      - name: set env
        run: echo "::set-env name=GTK_LIB_DIR::${{ github.workspace }}/vcpkg/installed/x64-windows/lib"
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose